app:
  replicaCount: 1
  selectorName: webapp
  service:
    type: NodePort
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
  image:
    repository: abdelazizomar/ejs-api-hub
    tag: "1"
    pullPolicy: Always

  env:
    - name: PORT
      configMapKey: PORT
    - name: TODO_MONGO_DB
      configMapKey: TODO_MONGO_DB
    - name: TODO_MONGO_CONNSTR
      configMapKey: TODO_MONGO_CONNSTR
    - name: WEATHER_API_KEY
      secretKey: WEATHER_API_KEY


mongo:
  app:
    replicasCount: 1
    image: mongo
  selectorName: mongodb
  service:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
  pv_pvc:
   storageClassName: standard
   capacity:
    storage: 1Gi
   accessModes:
    - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   hostPath:
    path: /data